services:
    db:
        image: postgres:17.2
        container_name: postgres-db
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}

        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
            - my-custom-network

    express-app:
        build: .
        container_name: express-app
        ports:
            - 8080:8080
        command: npm run dev
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - db
        networks:
            - my-custom-network

networks:
    my-custom-network:
